Game/urls.py
from django.conf.urls import url, include

from . import views


app_name = 'poker'
urlpatterns = [

    # /homepage/
    url(r'^$', views.index, name="index"),
    # /profile/
    url(r'^profile/$', views.profile, name="profile"),
    # /game/
    url(r'^game/$', views.game, name='game'),
    # /register/
    url(r'^register/$', views.UserFormView.as_view(), name="register"),
    # /login/
    url(r'^login/$', views.login_view, name='login'),
    # /logout/
    url(r'^logout/$', views.logout_view, name='logout'),


]

Poker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Game.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Game/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    first_name = models.CharField(max_length=200, default='')
    last_name = models.CharField(max_length=200, default='')
    country = models.CharField(max_length=200, default='')
    chips = models.IntegerField(default=0)
    profile_pic_url = models.CharField(max_length=800, default='')

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])
post_save.connect(create_profile, sender=User)

Game/forms.py
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, get_user_model, logout
from django import forms
from Game.models import UserProfile


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email','password']


class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=200)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user does not exist. Please register to continue.")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect Password.")
        return super(UserLoginForm, self).clean(*args, **kwargs)



class CreateProfileForm(forms.ModelForm):

     class Meta:
         model = UserProfile
         fields = ['first_name','last_name','country','chips','profile_pic_url']

Game/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import UserProfile
from django.contrib.auth import authenticate, login, get_user_model, logout
from forms import *
from django.views.generic import View
from django.contrib import messages


def index(request):
    return render(request, 'game/index.html')

class UserFormView(View):
    form_class = UserForm
    template_name = 'game/registration.html'

    # display new user form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})

    #add new user to database
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            #format input data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            #authenticate user
            user = authenticate(username=username,password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('poker:index')
        return render(request, self.template_name, {'form': form})


def login_view(request):
    form = UserLoginForm(request.POST)
    print(request.user.is_authenticated())
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            login(request,user)
            print(request.user.is_authenticated())
            return redirect('poker:profile')
        else:
            return render(request, 'game/login.html', {'form': form, 'context': 'Username and password do not match'})
    else:
        return render(request, 'game/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return render(request, 'game/logout.html')


@login_required(login_url='/login/')
def profile(request):
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)
    if request.method == 'POST':
        form = CreateProfileForm(request.POST, instance=profile)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect('poker:profile')
    else:
        form = CreateProfileForm(instance=profile)
    return render(request, 'game/profile.html', {"form":form,'user':request.user})


@login_required(login_url='/login/')
def game(request):
    return render(request, 'game/game.html', {'user':request.user})

Game/templates/game/account_form.html
{% extends 'game/base.html' %}
{% block title %}Account{% endblock %}
{% block content %}
    <div class = "container-fluid">
    <div class = "row">
        <div class = "col-md-7 col-sm-12">
            <div class = "panel panel-default">
                <div class = "panel-body">

                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

Game/templates/game/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Online Poker{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="{% static 'css/poker.css' %}" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="{% static 'js/game.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">

        {% if user.is_authenticated %}
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'poker:index' %}"><img class="img-header" src="{% static "img/chip.png" %}" alt=""></a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'poker:profile' %}">Profile</a>
            </li>
              <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'poker:game' %}">New Game</a>
            </li>
              <li class="nav-item">
              <a class="nav-link js-scroll-trigger logout" href="{% url 'poker:logout'%}">Logout</a>
            </li>
          </ul>
        </div>
      </div>

            {% else %}
              <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'poker:index' %}"><img class="img-header" src="{% static "img/chip.png" %}" alt=""></a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'poker:login'%}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'poker:register' %}">Register</a>
            </li>
          </ul>
        </div>
      </div>
        {% endif %}

    </nav>
{% block content %}
{% endblock %}
</body>
</html>

Game/templates/game/form-template.html
{% for field in form %}
    <div class = "form-group">
        <label class = "control-label col-sm-2">{{ field.label_tag }}</label>
        <div class = "col-sm-12">{{ field }}</div>
    </div>
{% endfor %}

Game/templates/game/game.html
{% extends 'game/base.html' %}
{% load staticfiles %}
{% block title %}Game{% endblock %}
{% block content %}
    <div class = "container">
        <div class = "row">
            <div class = "betting-table col-md-3">
                <h4>Your Bet</h4>
                <span id='more'>+</span>
                <div id = 'bet' class = 'bet-money'>0</div>
                <span id='less'>-</span>
            </div>
            <div class = "col-md-6">
                <div class = "row">
                    <h4 class="dealerHeading"> Dealer's Cards </h4>
                    <div class='dealer-cards'>
                        <div class='card card1'></div>
                        <div class='card flipped card2'></div>
                        <div class='new-cards'></div>
                        <div id='dealerTotal' class='dealer-total'></div>
                    </div>
                </div>
                <div class = "row">
                    <h4 class = "playerHeading"> {{ user }}'s Cards </h4>
                    <div class='player-cards'>
                        <div class='card card1'></div>
                        <div class='card card2'></div>
                        <div class='new-cards'></div>
                        <div id='playerTotal' class='player-total'></div>
                    </div>
                </div>
            </div>
            <div class = "betting-table col-md-3">
                <h4>Available Chips</h4>
                <div id='money' class='money'>{{ user.userprofile.chips }}</div>
            </div>
        </div>
        <div class = "row">
            <div class = "col-md-12">
                <div class='buttons gameaction'>
                    <span id='hit'><button class = "btnaction">Hit</button></span>
        		    <span id='stand'><button class = "btnaction">Stand</button></span>
    	        </div>
            </div>
        </div>
    </div>
{% endblock %}

Game/templates/game/index.html
{% extends 'game/base.html' %}
{% block title %}Home Page{% endblock %}
{% load staticfiles%}
{% block content %}
    <main>
    <header class="masthead">
      <div class="container">
        <img class="img-fluid" src="{% static "img/blackjack.png" %}" alt="">
        <div class="intro-text">
          <span class="name">New Game</span>
          <a class = "newGameLink" href = "{% url 'poker:game' %}"><button type = "submit" class = "newGame">START</button></a>
          <span class="skills">yalla, time to win some money</span>
        </div>
      </div>
    </header>
    </main>
{% endblock %}

Game/templates/game/login.html
{% extends 'game/base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
    <div class = "container-fluid">
    <div class = "row">
        <div class = "col-md-12 col-sm-12">
            <div class = "panel panel-default">
                <div class = "panel-body">

                    <form class = "form-horizontal" action = "" method="post">
                        {% csrf_token %}
                        {% include 'game/form-template.html'%}
                        <div class = "form-group">
                            <div class = "col-sm-12">
                                <button type = "submit" class="btn btn-success">Login</button>
                            </div>
                        </div>
                    </form>
                    {% if context %}
                        {{ context }}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

Game/templates/game/logout.html
{% extends 'game/base.html' %}
{% block title %}Logged Out{% endblock %}
{% block content %}
    <h1 class = "logout">Successfully Logged Out!</h1>
{% endblock %}

Game/templates/game/profile.html
{% extends 'game/base.html' %}
{% block title %}Profile{% endblock %}
{% block content %}
    <main>
    <h1 class = "heading">Welcome to your Profile {{ user.userprofile.first_name }}</h1>
        <div class = profinfo>
            <div class = "profile_pic"><img class = "profile_pic" src = '{{ user.userprofile.profile_pic_url }}'></div>
            <div class = "username">Username:   {{ user }}</div>
            <div class = "country">Country:   {{ user.userprofile.country }}</div>
            <div class = "firstname">Name:   {{ user.userprofile.first_name }} {{ user.userprofile.last_name }}</div>
            <div class = chips>Chips:   {{ user.userprofile.chips }}</div>
        </div>


    <div class = "col-md-12 col-sm-12 editprofile">
        <button class="btn btn-success" id = "collapse">Create/Edit Account</button>
            <div class = "panel panel-default">
                <div class = "panel-body">
                    <form class = "form1 form-horizontal collapseForm" action = "" method="post">
                        <h4>Profile Info: </h4>
                        {% csrf_token %}
                        {% include 'game/form-template.html'%}
                        <div class = "form-group">
                            <div class = "col-sm-12">
                                <button type = "submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>

    </main>
{% endblock %}

Game/templates/game/registration.html
{% extends 'game/base.html' %}
{% block title %}Register{% endblock %}
{% block content %}
    <h3>Create a New Account</h3>
{% endblock %}